/*8A: caso 1*/
select fecha_entrega_propiedad   from propiedad 
WHERE FECHA_ENTREGA_PROPIEDAD LIKE '%%/%%/22' ORDER BY
FECHA_ENTREGA_PROPIEDAD ASC;
/*8A: caso 2*/
select FECINI_ARRIENDO from propiedad_arrendada 
WHERE FECINI_ARRIENDO LIKE '%%/%%/22'
order by FECINI_ARRIENDO ASC;


/*CASO 2*/
SELECT NUMRUT_CLI RUT,NOMBRE_CLI || ' ' || APPATERNO_CLI || ' ' || APMATERNO_CLI
NOMBRE_CLIENTE, RENTA_CLI RENTA,FONOFIJO_CLI TELEFONO_FIJO,CELULAR_CLI CELULAR 
FROM CLIENTE CL INNER JOIN ESTADO_CIVIL EC ON 
EC.ID_ESTCIVIL = CL.ID_ESTCIVIL 
WHERE EC.DESC_ESTCIVIL ='Soltero' OR EC.DESC_ESTCIVIL ='Separado' 
OR EC.DESC_ESTCIVIL ='Divorciado' AND CL.RENTA_CLI >= 800000 ORDER BY
 CL.APPATERNO_CLI ASC,
 NOMBRE_CLI DESC ;



/*CASO 3 SIMULACION 1*/
SELECT NOMBRE_EMP || ' ' ||  APPATERNO_EMP || ' '
|| APMATERNO_EMP NOMBRE_EMPLEADO,SUELDO_EMP SUELDO_ACTUAL,SUELDO_EMP * 0.085 +  SUELDO_EMP
SUELDO_REAJUSTADO,(SUELDO_EMP * 0.085 +  SUELDO_EMP) - SUELDO_EMP AUMENTO FROM EMPLEADO 
ORDER BY (SUELDO_EMP * 0.085 +  SUELDO_EMP) - SUELDO_EMP DESC ;


SELECT * FROM ESTADO_CIVIL

/*CASO 3 SIMULACION 2*/

SELECT NOMBRE_EMP || ' ' ||  APPATERNO_EMP || ' '
|| APMATERNO_EMP NOMBRE_EMPLEADO,SUELDO_EMP SUELDO_ACTUAL, 
SUELDO_EMP * 0.2 +  SUELDO_EMP
SUELDO_REAJUSTADO,(SUELDO_EMP * 0.20 +  SUELDO_EMP) - SUELDO_EMP AUMENTO
FROM EMPLEADO WHERE
SUELDO_EMP > 200000 AND SUELDO_EMP <=400000 
ORDER BY (SUELDO_EMP * 0.085 +  SUELDO_EMP) - SUELDO_EMP DESC ;

/*CASO 4 SIMULACION 2*/
SELECT E.NUMRUT_EMP || '-' || E.DVRUT_EMP RUN_EMPLEADO,E.NOMBRE_EMP || ' ' || 
E.APPATERNO_EMP || ' ' ||
E.APMATERNO_EMP NOMBRE_EMPLEADO,E.SUELDO_EMP SALARIO_ACTUAL,
(SUELDO_EMP * 0.20 +  SUELDO_EMP) - SUELDO_EMP BONIFICACION_EXTRA
FROM EMPLEADO E
INNER JOIN CATEGORIA_EMPLEADO CA
ON CA.ID_CATEGORIA_EMP= E.ID_CATEGORIA_EMP
WHERE SUELDO_EMP <500000 AND CA.DESC_CATEGORIA_EMP != 'Ejecutivo de Arriendo'
ORDER BY E.APPATERNO_EMP ASC  ;

SELECT * FROM EMPLEADO;
/*CASO 5 INFORME 1*/
SELECT NRO_PROPIEDAD,FECHA_ENTREGA_PROPIEDAD,DIRECCION_PROPIEDAD DIRECCION, SUPERFICIE,
NRO_DORMITORIOS CANTIDAD_DE_DORMITORIOS,NRO_BANOS CANTIDAD_DE_BAÑOS
FROM PROPIEDAD WHERE FECHA_ENTREGA_PROPIEDAD LIKE '%%/%%/22'
ORDER BY FECHA_ENTREGA_PROPIEDAD ASC;

/*CASO 5 INFORME 2*/
SELECT NRO_PROPIEDAD,DIRECCION_PROPIEDAD DIRECCION, SUPERFICIE,
NRO_DORMITORIOS CANTIDAD_DE_DORMITORIOS,NRO_BANOS CANTIDAD_DE_BAÑOS,VALOR_ARRIENDO
FROM PROPIEDAD WHERE FECHA_ENTREGA_PROPIEDAD LIKE '%%/02/10';

select * from propiedad