/*caSso 1 */
SELECT NUMRUN_CLI||'-'||DVRUN_CLI RUT_CLIENTE, PNOMBRE_CLI || ' ' || SNOMBRE_CLI || ' '||APPATERNO_CLI ||
' '|| APMATERNO_CLI NOMBRE_COMPLETO_CLIENTE, FECHA_NAC_CLI FECHA_NACIMIENTO FROM
CLIENTE WHERE FECHA_NAC_CLI LIKE '21/08/%%' ORDER BY APPATERNO_CLI ASC;
/*CASO 2*/
SELECT NUMRUN_EMP||'-'||DVRUN_EMP RUT_CLIENTE, PNOMBRE_EMP || ' ' || SNOMBRE_EMP
|| ' '||APPATERNO_EMP ||
' '|| APMATERNO_EMP NOMBRE_COMPLETO_CLIENTE,SUELDO_BASE,
TRUNC(SUELDO_BASE/100000)
PORCENTAJE_MOVILIZACION,
ROUND(SUELDO_BASE *( TRUNC(SUELDO_BASE/100000)/100)+ SUELDO_BASE)-SUELDO_BASE VALOR_MOVILIZACION
FROM EMPLEADO ORDER BY TRUNC(SUELDO_BASE/100000) DESC;
/*CASO 3*/

SELECT NUMRUN_EMP||'-'||DVRUN_EMP RUT_CLIENTE, PNOMBRE_EMP || ' ' || SNOMBRE_EMP
|| ' '||APPATERNO_EMP ||
' '|| APMATERNO_EMP NOMBRE_COMPLETO_CLIENTE,SUELDO_BASE,FECHA_NAC FECHA_NACIMIENTO,
SUBSTR(PNOMBRE_EMP,1,3)||FECHA_CONTRATO+2||TRUNC(SUELDO_BASE,-3)-1||SUBSTR(APPATERNO_EMP,-3)
||extract(month from sysdate) CLAVE FROM EMPLEADO

SELECT NUMRUN_EMP||'-'||DVRUN_EMP RUT_CLIENTE, PNOMBRE_EMP || ' ' || SNOMBRE_EMP
|| ' '||APPATERNO_EMP ||
' '|| APMATERNO_EMP NOMBRE_COMPLETO_CLIENTE,SUELDO_BASE,FECHA_NAC FECHA_NACIMIENTO,
SUBSTR(PNOMBRE_EMP,1,3)||LENGTH(PNOMBRE_EMP)||'*'||SUBSTR(cast(SUELDO_BASE as varchar(20)),-1)
||DVRUN_EMP||(2022 - (CAST(EXTRACT(YEAR FROM FECHA_CONTRATO)AS INTEGER)) ) USUARIO,
SUBSTR(CAST(NUMRUN_EMP AS VARCHAR(20)),3,1)||(CAST(EXTRACT(YEAR FROM FECHA_CONTRATO)AS INT))+ 2  ||
SUBSTR(cast((SUELDO_BASE-1) as varchar(20)),-3)||SUBSTR(APPATERNO_EMP,-2)||EXTRACT(MONTH FROM SYSDATE) CLAVE
FROM EMPLEADO ORDER BY APPATERNO_EMP ASC;
/*comprobando los años de contrato mas 2*/
SELECT PNOMBRE_EMP || ' ' || SNOMBRE_EMP
|| ' '||APPATERNO_EMP ||
' '|| APMATERNO_EMP NOMBRE_COMPLETO_CLIENTE,
FECHA_CONTRATO ,
(CAST(EXTRACT(YEAR FROM FECHA_CONTRATO)AS INT))+ 2 
FROM EMPLEADO
/****************************************************/
/*CASO 4*/
SELECT EXTRACT(YEAR FROM SYSDATE) ANNO_PROCESO,NRO_PATENTE,VALOR_ARRIENDO_DIA
VALOR_ARRIENDO_DIA_SR,
VALOR_GARANTIA_DIA VALOR_GARANTIA_DIA_SR,
 CAST(EXTRACT(YEAR FROM SYSDATE) AS INT)- ANIO ANNOS_ANTIGUEDAD ,
VALOR_ARRIENDO_DIA *  ((100-(CAST(EXTRACT(YEAR FROM SYSDATE) AS INT)- ANIO))/100 ) VALOR_ARRIENDO_DIA_CR,
VALOR_GARANTIA_DIA *  ((100-(CAST(EXTRACT(YEAR FROM SYSDATE) AS INT)- ANIO))/100 ) VALOR_GARANTIA_DIA_CR
FROM CAMION ORDER BY  CAST(EXTRACT(YEAR FROM SYSDATE) AS INT)- ANIO DESC,
 NRO_PATENTE ASC;
 
 /*CASO 5*/
 SELECT EXTRACT(MONTH FROM SYSDATE)||'/'||EXTRACT( YEAR FROM SYSDATE)
 MES_ANNO_PROCESO,
 C.NRO_PATENTE,
 AC.FECHA_INI_ARRIENDO,
 AC.DIAS_SOLICITADOS,
 AC.FECHA_DEVOLUCION,
  CAST(EXTRACT(DAY FROM AC.FECHA_DEVOLUCION)AS INT)-
 CAST(EXTRACT(DAY FROM AC.FECHA_INI_ARRIENDO)AS INT)DIAS_ATRASO,
25500*
(  CAST(EXTRACT(DAY FROM AC.FECHA_DEVOLUCION)AS INT)-
 CAST(EXTRACT(DAY FROM AC.FECHA_INI_ARRIENDO)AS INT))
VALOR_MULTA
 FROM  CAMION C INNER JOIN ARRIENDO_CAMION AC
 ON C.NRO_PATENTE = AC.NRO_PATENTE
 WHERE AC.FECHA_DEVOLUCION LIKE '%%/07/%%'
ORDER BY AC.FECHA_INI_ARRIENDO ASC,NRO_PATENTE ASC